### PR TITLE
Added support for async suggestion finding

### PR DESCRIPTION
**Pull request by gauris26**
- Added for async query searching suggestions
- Prevent that just selected option remains in the overlay list (This could produce duplicate key issue if user clicks twice an already selected chip).

### CODE REVIEW

**Comment by zsoerenm** [comment]
Great, this looks like an easy fix.
Could you actually use `FutureOr<T>`?
That way both async and sync data is supported.

**Comment by gauris26** [comment]
> Great, this looks like an easy fix. Could you actually use `FutureOr<T>`: https://stackoverflow.com/questions/59213196/what-is-the-purpose-of-futureor ? That way both async and sync data is supported.

Yeah, that could work better. Added, thanks for the suggestion.

**Comment by zsoerenm** [comment]
Thanks!
I will test it this evening.

**Comment by zsoerenm** [comment]
I have merged your pull request. Locally the test run fine. However, here at Github they fail:
https://github.com/zsoerenm/chips_input/runs/5309673719?check_suite_focus=true
Can you reproduce this with `flutter test`?
If this error gets fixed I will upload a new version.

**Comment by zsoerenm** [comment]
Alright, never mind. It was because the Flutter version, that Github used, was old. It is running fine now.

**Pull request merged**
